# -*- coding: utf-8 -*-
"""base94_21 - Pós IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4cKWIIVWOUXdqM_wkg82OnTeonp5Lgy

# 📘 Projeto de Mineração de Dados – Análise Financeira Completa  
### **Notebook Profissional – Pós IA Aplicada**

---

# 📑 **Sumário**
1. [Instalação de Bibliotecas](#sec1)  
2. [Upload e Carregamento do Banco de Dados](#sec2)  
3. [Exploração Inicial dos Dados](#sec3)  
4. [Ranking de Retorno, Volatilidade e Liquidez](#sec4)  
5. [Volatilidade Histórica, ATR e Risco](#sec5)  
6. [Detecção de Anomalias](#sec6)  
7. [Indicadores Técnicos (RSI, MACD, MM, Bollinger)](#sec7)  
8. [Correlação Entre Ativos](#sec8)  
9. [Clusterização de Ações](#sec9)  
10. [Detecção de Volume Spike](#sec10)  
11. [Retorno Acumulado Comparativo](#sec11)  
12. [Simulação Estratégia MM9 x MM21](#sec12)  
13. [Dashboard Financeiro Interativo](#sec13)  
14. [Event Study](#sec14)  
15. [Microestrutura: Spread e Pressão](#sec15)  
16. [Detecção de Gaps](#sec16)

## <a name='sec1'></a>📦 1. Instalação de Bibliotecas

### 📦 1. Instalação de Bibliotecas

**O que o código faz:** Este trecho instala as bibliotecas Python necessárias para o projeto. `ydata-profiling` é para análise exploratória de dados, `pandas_ta` para indicadores técnicos financeiros, `plotly` e `seaborn` para visualização, e `scikit-learn` para aprendizado de máquina (como clusterização).

**Insight:** Garante que todas as ferramentas e funções que serão usadas nas análises subsequentes estejam disponíveis no ambiente, preparando o terreno para a mineração de dados.
"""

!pip install ydata-profiling pandas_ta plotly seaborn scikit-learn

"""## <a name='sec2'></a>📁 2. Upload e Carregamento do Banco de Dados"""



import sqlite3, pandas as pd, numpy as np
from google.colab import drive

# Monta o Google Drive
#drive.mount('/content/drive')

# --- ATENÇÃO: Substitua este caminho pelo caminho real do seu arquivo .db no Google Drive ---
#db_path = '/content/drive/MyDrive/Colab Notebooks/Pós Graduação IA Aplicada/2 - Big Data e Mineração de Dados/bolsa_94_21.db' # Exemplo: /content/drive/MyDrive/MinhaPasta/meu_arquivo.db
db_path = '/content/bolsa_94_21.db'
try:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    print(f"Conectado ao banco de dados no Google Drive: {db_path}")
except Exception as e:
    print(f"Erro ao conectar ao banco de dados: {e}")
    print("Por favor, verifique o caminho do arquivo no seu Google Drive e se ele está montado corretamente.")



cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tabelas = [t[0] for t in cursor.fetchall()]
tabelas

dfs = {}
for tabela in tabelas:
    dfs[tabela] = pd.read_sql_query(f"SELECT * FROM {tabela}", conn)

df_cotacao = dfs.get("cotacao")
df_papel = dfs.get("papel")
df_empresa = dfs.get("empresa")
df_evento = dfs.get("evento")
df_eventocotacao = dfs.get("eventocotacao")

df_cotacao["data"] = pd.to_datetime(df_cotacao["data"])
df_cotacao = df_cotacao.sort_values(["cd_papel","data"])
df_cotacao.head()

"""## <a name='sec3'></a>🔍 3. Exploração Inicial (EDA)

**O que o código faz:** A função `df_cotacao.describe()` gera um resumo estatístico das colunas numéricas do DataFrame `df_cotacao`. Isso inclui contagem, média, desvio padrão, valores mínimo/máximo e quartis.

**Insight:** Oferece uma visão rápida da distribuição e das características básicas dos dados, ajudando a identificar possíveis problemas como valores ausentes, outliers extremos ou faixas de valores inesperadas, antes de análises mais aprofundadas.
"""

df_cotacao.describe()

from ydata_profiling import ProfileReport
from IPython.display import display

profile = ProfileReport(df_cotacao, title="Relatório de Profiling do df_cotacao")
display(profile)

print("A análise do ydata-profiling foi exibida abaixo. Caso queira salvar o HTML, descomente a linha 'profile.to_file(...)' ")
profile.to_file("ydata_profiling_report.html")

import matplotlib.pyplot as plt
import seaborn as sns

# Variáveis selecionadas para boxplots
variaveis_para_boxplot = ['fechamento', 'volume', 'qtd_negocios']

plt.figure(figsize=(15, 5))
for i, col in enumerate(variaveis_para_boxplot):
    plt.subplot(1, 3, i + 1)
    sns.boxplot(y=df_cotacao[col])
    plt.title(f'Boxplot de {col}')
    plt.ylabel('') # Remove default y-label as it's redundant
plt.tight_layout()
plt.show()

print("Os boxplots acima mostram a distribuição e a presença de outliers para o preço de fechamento, volume e quantidade de negócios. Valores fora dos 'bigodes' do boxplot são considerados potenciais outliers.")

print("### Top 10 maiores valores para Fechamento, Volume e Quantidade de Negócios ###\n")

variables_to_analyze = ['fechamento', 'volume', 'qtd_negocios']

for var in variables_to_analyze:
    print(f"--- Top 10 Maiores Valores de {var.replace('_', ' ').title()} ---")

    # Seleciona as 10 maiores cotações para a variável atual
    top_10_values = df_cotacao.sort_values(by=var, ascending=False).head(10)

    # Mescla com df_papel e df_empresa para obter informações adicionais
    top_10_details = top_10_values.merge(df_papel, on='cd_papel', how='left') \
                                  .merge(df_empresa, on='cd_empresa', how='left')

    # Seleciona as colunas relevantes para exibição
    display_columns = ['data', 'codigo', 'empresa', var, 'abertura', 'maximo', 'minimo', 'volume', 'qtd_negocios']
    print(top_10_details[display_columns].to_markdown(index=False))
    print("\n")

"""## <a name='sec4'></a>📈 4. Ranking de Retorno, Volatilidade e Liquidez

Calcula o retorno diário (`pct_change`), o retorno acumulado (`(1+x).prod() - 1`), a volatilidade (desvio padrão dos retornos), o volume médio e o número médio de negócios para cada ativo (`cd_papel`). Em seguida, cria um DataFrame de ranking e mostra os 10 ativos com maior retorno acumulado.

Permite identificar rapidamente os ativos com melhor desempenho histórico, os mais arriscados (voláteis) e os mais negociados (líquidos).
"""

df_cotacao["retorno"] = df_cotacao.groupby("cd_papel")["fechamento"].pct_change()

ret_acum = df_cotacao.groupby("cd_papel")["retorno"].apply(lambda x: (1+x).prod() - 1)
vol = df_cotacao.groupby("cd_papel")["retorno"].std()
liq_vol = df_cotacao.groupby("cd_papel")["volume"].mean()
liq_neg = df_cotacao.groupby("cd_papel")["qtd_negocios"].mean()

ranking = pd.DataFrame({
    "retorno_acumulado": ret_acum,
    "volatilidade": vol,
    "volume_medio": liq_vol,
    "negocios_medio": liq_neg
}).dropna()

ranking.sort_values("retorno_acumulado", ascending=False).head(10)

"""## <a name='sec5'></a>📉 5. Volatilidade Histórica, ATR e Risco

Calcula o True Range (variação entre máxima e mínima do dia), o Average True Range (ATR) para medir a volatilidade média e o Coeficiente de Variação (CV), que é o desvio padrão dividido pela média. Essas métricas são agrupadas por ativo.

Fornece medidas robustas de risco e volatilidade dos ativos. O ATR é útil para definir stop-losses, enquanto o CV permite comparar a dispersão dos preços de ativos com médias diferentes, ajudando a entender o risco relativo de cada investimento.
"""

df_cotacao["true_range"] = df_cotacao["maximo"] - df_cotacao["minimo"]

atr = df_cotacao.groupby("cd_papel")["true_range"].rolling(14).mean().reset_index()
atr = atr.groupby("cd_papel")["true_range"].mean()

cv = df_cotacao.groupby("cd_papel")["fechamento"].std() / df_cotacao.groupby("cd_papel")["fechamento"].mean()

risk_df = pd.DataFrame({
    "ATR": atr,
    "Coef_Variacao": cv
}).dropna()

risk_df.head()

"""## <a name='sec6'></a>⚠️ 6. Detecção de Anomalias

Para cada ativo, calcula a média e o desvio padrão do volume de negociação. Em seguida, identifica os dias em que o volume excedeu a média em mais de 3 desvios padrão, marcando-os como "Volume Spike".

Detecta eventos de negociação atípica que podem indicar notícias importantes, grandes movimentos de investidores institucionais ou mudanças significativas no sentimento do mercado. Esses "spikes" merecem análise mais detalhada para entender o que os causou.
"""

anom_list = []

for papel, grupo in df_cotacao.groupby("cd_papel"):
    media = grupo["volume"].mean()
    desvio = grupo["volume"].std()

    spikes = grupo[grupo["volume"] > media + 3*desvio]
    spikes["anomalia"] = "Volume Spike"

    anom_list.append(spikes)

anomalias = pd.concat(anom_list)
anomalias.head()

"""## <a name='sec7'></a>📊 7. Indicadores Técnicos (RSI, MACD, Bandas, MMs)

Adiciona vários indicadores técnicos ao DataFrame de cotações para cada ativo: Índice de Força Relativa (RSI), Convergência/Divergência de Médias Móveis (MACD), Médias Móveis de 9 e 21 períodos (MM9, MM21) e Bandas de Bollinger (bb_upper, bb_mid, bb_low).

Estes indicadores são ferramentas essenciais na análise técnica, ajudando a identificar tendências de preço, condições de sobrecompra/sobrevenda, momentum e níveis de volatilidade.
"""

import pandas_ta as ta
import numpy as np # Import numpy for NaN values

ind=[]
for papel, grp in df_cotacao.groupby("cd_papel"):
    g = grp.copy()
    g["rsi"] = ta.rsi(g["fechamento"], 14)

    # Calculate MACD and handle cases where it might return None
    macd_result = ta.macd(g["fechamento"])
    if macd_result is not None:
        g["macd"] = macd_result["MACD_12_26_9"]
    else:
        # Fill 'macd' column with NaN if calculation is not possible
        g["macd"] = pd.Series(np.nan, index=g.index)

    g["mm9"] = g["fechamento"].rolling(9).mean()
    g["mm21"] = g["fechamento"].rolling(21).mean()

    # Calculate Bollinger Bands and handle cases where it might return None
    bb_result = ta.bbands(g["fechamento"])
    if bb_result is not None:
        g["bb_upper"], g["bb_mid"], g["bb_low"] = bb_result.iloc[:,0], bb_result.iloc[:,1], bb_result.iloc[:,2]
    else:
        # Fill Bollinger Band columns with NaN if calculation is not possible
        g["bb_upper"] = pd.Series(np.nan, index=g.index)
        g["bb_mid"] = pd.Series(np.nan, index=g.index)
        g["bb_low"] = pd.Series(np.nan, index=g.index)

    ind.append(g)

df_ind = pd.concat(ind).sort_values(["cd_papel","data"])
df_ind.head()

"""## <a name='sec8'></a>🧩 8. Correlação Entre Ativos

Cria uma tabela dinâmica dos retornos diários de todos os ativos e, em seguida, calcula a matriz de correlação entre eles. Esta matriz é visualizada através de um mapa de calor (heatmap).

Entender a correlação entre ativos é vital para a diversificação de portfólio. Ativos com baixa ou correlação negativa são desejáveis para reduzir o risco geral do portfólio, enquanto alta correlação pode indicar que os ativos se movem em sincronia.
"""

import seaborn as sns
import matplotlib.pyplot as plt

ret_pivot = df_cotacao.pivot_table(index="data", columns="cd_papel", values="retorno")
cor = ret_pivot.corr()

plt.figure(figsize=(14,8))
sns.heatmap(cor, cmap="coolwarm")
plt.title("Correlação Entre Ativos")
plt.show()

"""## <a name='sec9'></a>🧬 9. Clusterização de Ações

Utiliza os retornos acumulados e a volatilidade de cada ativo, padroniza esses dados e aplica o algoritmo K-Means para agrupar os ativos em 5 clusters. O número do cluster é adicionado ao DataFrame `cluster_base`.

Ajuda a identificar grupos de ativos com perfis de risco e retorno semelhantes. Isso pode ser usado para entender a estrutura do mercado, otimizar a diversificação de portfólio ou desenvolver estratégias de investimento focadas em características específicas de clusters.
"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

cluster_base = ranking[["retorno_acumulado","volatilidade"]].dropna()

sc = StandardScaler()
scaled = sc.fit_transform(cluster_base)

km = KMeans(n_clusters=5, random_state=42)
cluster_base["cluster"] = km.fit_predict(scaled)

cluster_base.head()

"""## <a name='sec10'></a>🔎 10. Volume Spike – Detector

Exibe o cabeçalho do DataFrame `anomalias`, que já foi gerado na Seção 6 e contém os registros de dias com picos de volume.

Reafirma a identificação de momentos incomuns de alta atividade de negociação para cada papel, o que pode sinalizar eventos importantes que influenciam o preço e que valem a pena investigar mais a fundo.
"""

spike_df = anomalias[["cd_papel","data","volume","anomalia"]]
spike_df.head()

"""## <a name='sec11'></a>📈 11. Retorno Acumulado Comparativo

Calcula o retorno acumulado diário para cada ativo, aplicando a função `cumprod()` (produto cumulativo) aos retornos diários. Isso mostra a evolução do valor de um investimento hipotético ao longo do tempo.

Permite visualizar e comparar o desempenho histórico de diferentes ativos como se um investimento inicial tivesse sido feito, mostrando o crescimento (ou perda) do capital ao longo do tempo. É fundamental para avaliar a performance de um ativo ou portfólio.
"""

ret_acum_daily = df_cotacao.groupby("cd_papel")["retorno"].apply(lambda x: (1+x).cumprod())
ret_acum_daily = ret_acum_daily.reset_index(name="retorno_acum")
ret_acum_daily.head()

"""## <a name='sec12'></a>⚙️ 12. Estratégia MM9 x MM21

Implementa uma estratégia de negociação baseada no cruzamento de médias móveis de 9 e 21 períodos. Um sinal de compra é gerado quando a MM9 cruza acima da MM21. A coluna `posicao` simula a manutenção da posição, e `ret_estrategia` calcula o retorno diário da estratégia.
Simula uma estratégia de negociação comum para avaliar seu potencial de lucro. Permite entender como os sinais de indicadores técnicos podem ser traduzidos em decisões de compra/venda e quais retornos poderiam ser esperados.
"""

estr = df_ind.copy()
estr["sinal"] = (estr["mm9"] > estr["mm21"]).astype(int)
estr["posicao"] = estr.groupby("cd_papel")["sinal"].shift(1)
estr["ret_estrategia"] = estr["posicao"] * estr["retorno"]
estr.head()

"""## <a name='sec13'></a>📊 13. Dashboard Financeiro – Plotly

Seleciona um ativo (o primeiro `cd_papel` único) e cria um gráfico de candlestick interativo usando a biblioteca Plotly. O gráfico exibe os preços de abertura, máxima, mínima e fechamento ao longo do tempo.

**Insight:** Fornece uma visualização detalhada do movimento dos preços de um ativo, essencial para a análise técnica. Gráficos de candlestick ajudam a identificar padrões de preço, tendências e pontos de virada no mercado.
"""

import plotly.graph_objects as go

papel = df_cotacao["cd_papel"].unique()[0]
subset = df_cotacao[df_cotacao["cd_papel"] == papel]

fig = go.Figure(data=[go.Candlestick(
    x=subset["data"],
    open=subset["abertura"],
    high=subset["maximo"],
    low=subset["minimo"],
    close=subset["fechamento"]
)])

fig.update_layout(
    title=f"Gráfico de Candles — {papel}",
    xaxis_title="Data",
    yaxis_title="Preço"
)

fig.show()

"""## <a name='sec14'></a>📅 14. Event Study

### 📅 14. Event Study

**O que o código faz:** Combina os DataFrames `df_eventocotacao` e `df_evento` para juntar informações detalhadas sobre eventos corporativos (como dividendos, bonificações) com os dados de cotação dos respectivos papéis.

**Insight:** Prepara os dados para analisar o impacto de eventos específicos (ex: anúncio de dividendos, desdobramentos de ações) no preço dos ativos. Isso ajuda a entender como o mercado reage a informações corporativas importantes.
"""

df_events = df_eventocotacao.merge(df_evento, on="cd_evento", how="left")
df_events.head()

"""## <a name='sec15'></a>📉 15. Microestrutura – Spread e Pressão

### 📉 15. Microestrutura – Spread e Pressão

**O que o código faz:** Calcula o "spread" (diferença entre preço de oferta de venda e compra), a "pressão de compra" (fechamento menos oferta de compra) e a "pressão de venda" (oferta de venda menos fechamento) para cada cotação.

**Insight:** Essas métricas fornecem informações sobre a liquidez do mercado e a dinâmica de oferta e demanda no nível micro. Um spread menor indica maior liquidez, enquanto as pressões indicam o lado do mercado que está dominando a formação do preço.
"""

micro = df_cotacao.copy()
micro["spread"] = micro["oferta_venda"] - micro["oferta_compra"]
micro["pressao_compra"] = micro["fechamento"] - micro["oferta_compra"]
micro["pressao_venda"] = micro["oferta_venda"] - micro["fechamento"]
micro.head()

"""## <a name='sec16'></a>🕳️ 16. Detecção de Gaps

### 🕳️ 16. Detecção de Gaps

**O que o código faz:** Calcula a diferença entre o preço de abertura de um dia e o preço de fechamento do dia anterior para cada ativo, identificando "gaps" no preço.

**Insight:** Gaps de preço são descontinuidades que podem ser causadas por notícias ou eventos que ocorrem fora do horário de negociação. A análise de gaps é usada por traders para identificar padrões de continuação ou reversão de tendência.
"""

gaps = df_cotacao.copy()
gaps["fech_ant"] = gaps.groupby("cd_papel")["fechamento"].shift(1)
gaps["gap"] = gaps["abertura"] - gaps["fech_ant"]
gaps.dropna().head()

# Criando uma pasta para organizar (opcional, se rodar local)
import os
os.makedirs('relatorios_csv', exist_ok=True)

# Exportando os principais DataFrames
ranking.to_csv('relatorios_csv/1_ranking_performance.csv')
risk_df.to_csv('relatorios_csv/2_risco_atr.csv')
anomalias.to_csv('relatorios_csv/3_anomalias_volume.csv', index=False)
df_ind.to_csv('relatorios_csv/4_indicadores_tecnicos.csv', index=False)
cluster_base.to_csv('relatorios_csv/5_clusters_acoes.csv')
cor.to_csv('relatorios_csv/6_matriz_correlacao.csv')
estr.to_csv('relatorios_csv/7_backtest_estrategia.csv', index=False)
micro.to_csv('relatorios_csv/8_microestrutura.csv', index=False)

print("Arquivos CSV gerados com sucesso!")